# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: saturn_sync_protocol/v1/grpc_controller.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n-saturn_sync_protocol/v1/grpc_controller.proto\x12\x17saturn_sync_protocol.v1\"\x07\n\x05\x45mpty2\\\n\x0eGRPCController\x12J\n\x08Shutdown\x12\x1e.saturn_sync_protocol.v1.Empty\x1a\x1e.saturn_sync_protocol.v1.EmptyB\x81\x02\n\x1b\x63om.saturn_sync_protocol.v1B\x13GrpcControllerProtoP\x01ZXgithub.com/wndhydrnt/saturn-sync-protocol/saturn_sync_protocol/v1;saturn_sync_protocolv1\xa2\x02\x03SXX\xaa\x02\x15SaturnSyncProtocol.V1\xca\x02\x15SaturnSyncProtocol\\V1\xe2\x02!SaturnSyncProtocol\\V1\\GPBMetadata\xea\x02\x16SaturnSyncProtocol::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'saturn_sync_protocol.v1.grpc_controller_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\033com.saturn_sync_protocol.v1B\023GrpcControllerProtoP\001ZXgithub.com/wndhydrnt/saturn-sync-protocol/saturn_sync_protocol/v1;saturn_sync_protocolv1\242\002\003SXX\252\002\025SaturnSyncProtocol.V1\312\002\025SaturnSyncProtocol\\V1\342\002!SaturnSyncProtocol\\V1\\GPBMetadata\352\002\026SaturnSyncProtocol::V1'
  _globals['_EMPTY']._serialized_start=74
  _globals['_EMPTY']._serialized_end=81
  _globals['_GRPCCONTROLLER']._serialized_start=83
  _globals['_GRPCCONTROLLER']._serialized_end=175
# @@protoc_insertion_point(module_scope)
