# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: saturn_sync_protocol/plugin/grpc_controller.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n1saturn_sync_protocol/plugin/grpc_controller.proto\x12\x06plugin\"\x07\n\x05\x45mpty2:\n\x0eGRPCController\x12(\n\x08Shutdown\x12\r.plugin.Empty\x1a\r.plugin.EmptyB\xa0\x01\n\ncom.pluginB\x13GrpcControllerProtoP\x01ZEgithub.com/wndhydrnt/saturn-sync-protocol/saturn_sync_protocol/plugin\xa2\x02\x03PXX\xaa\x02\x06Plugin\xca\x02\x06Plugin\xe2\x02\x12Plugin\\GPBMetadata\xea\x02\x06Pluginb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'saturn_sync_protocol.plugin.grpc_controller_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\ncom.pluginB\023GrpcControllerProtoP\001ZEgithub.com/wndhydrnt/saturn-sync-protocol/saturn_sync_protocol/plugin\242\002\003PXX\252\002\006Plugin\312\002\006Plugin\342\002\022Plugin\\GPBMetadata\352\002\006Plugin'
  _globals['_EMPTY']._serialized_start=61
  _globals['_EMPTY']._serialized_end=68
  _globals['_GRPCCONTROLLER']._serialized_start=70
  _globals['_GRPCCONTROLLER']._serialized_end=128
# @@protoc_insertion_point(module_scope)
