name: Pull Request

on:
  pull_request: {}

jobs:
  lint-protos:
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
    - uses: bufbuild/buf-setup-action@v1
    - uses: bufbuild/buf-lint-action@v1
