name: Release Integration Test Binary

on:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  upload:
    name: Upload
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23.x"
      - name: Build binaries
        env:
          VERSION: ${{ github.ref_name }}
        run: make build_all
      - name: Upload binaries
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload ${{ github.ref_name }} integration-test-${{ github.ref_name }}.*
          gh release upload ${{ github.ref_name }} sha256sums.txt
