name: Release

on:
  push:
    tags:
      - "*"

jobs:
  python:
    name: python
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - uses: Gr1N/setup-poetry@v8
      - env:
          PYTHON_PUBLISH_USERNAME: ${{ secrets.PYTHON_PUBLISH_USERNAME }}
          PYTHON_PUBLISH_PASSWORD: ${{ secrets.PYTHON_PUBLISH_PASSWORD }}
        run: poetry publish --build --username "$PYTHON_PUBLISH_USERNAME" --password "$PYTHON_PUBLISH_PASSWORD"
        working-directory: "./python"
